### ISSUE TITLE
Fast Calculation of Area Under ROC curve

### ISSUE THREAD

**Issue by mfrasco** [takayasaito/precrec#4]
The area under the ROC curve can be calculated directly from a vector of predictions and a vector of binary labels using the [Mann-Whitney U Test](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test#Area-under-curve_.28AUC.29_statistic_for_ROC_curves). Since this algorithm does not require calculating the ROC curve, it can provide a significant performance increase. My benchmarks on show that, on 10 million observations, this algorithm is six times faster than calculating AUROC with your package (18.3 seconds vs 2.9 seconds).

Would you be interested in adding a C++ implementation of this algorithm to your package? The speedup that this algorithm provides would be valuable for users who need to evaluate hundreds to thousands of models (e.g. with a grid search over a feature / hyper-parameter space).

If you are interested in outside contributions to your package, please let me know.

**Comment by takayasaito** [comment]
Thank you for an interesting suggestion and the link. I used the U statistic calculation of `wilcox.test` and compared with precrec on Linux and OS X. Precrec was faster in my test cases, but I could see it would perform much better with more efficient implementation. 

Precrec has an own C++ version of `rank` function internally, and by using it, I suppose the implementation of an efficient U statistic calculation shouldn't be too difficult. I may try to include this in precrec.

It would be great if you could contribute to the package. Unfortunately, I haven't prepared any proper documentations or policies for it, yet.

Below are the results of my test cases.

```R
# Test code
library(precrec)

# A sample of 10,000,000
samp1 <- create_sim_samples(1, 5000000, 5000000)
scores1 <- samp1$scores[[1]][[1]]
samp1.x <- scores1[1:5000000]
samp1.y <- scores1[5000001:10000000]

# Precrec
func_precrec <- function(samp) {
   curves <- evalmod(scores = samp$scores, labels = samp$labels)
   aucs <- auc(curves)
}

# U statistic
func_u <- function(x, y) {
   n.x <- as.numeric(length(x))
   n.y <- as.numeric(length(y))
   r <- rank(c(x, y))
   U <- sum(r[seq_along(x)]) - n.x * (n.x + 1) / 2
   uauc <- U / (n.x * n.y)
}
```

Linux - i7, 3.4GHz, 16 GB
```R
> # Process time
> system.time(res1 <- func_precrec(samp1))
   user  system elapsed 
  4.350   0.249   4.600 
> system.time(res2 <- func_u(samp1.x, samp1.y))
   user  system elapsed 
  7.943   0.059   8.004 
> 
> # AUCs
> res1
  modnames dsids curvetypes      aucs
1       m1     1        ROC 0.5001329
2       m1     1        PRC 0.5001741
> res2
[1] 0.5001329
```

OS X - i5, 2.4 GHz, 4 GB
```R
> # Process time
> system.time(res1 <- func_precrec(samp1))
   user  system elapsed 
  6.650   2.140   9.878 
> system.time(res2 <- func_u(samp1.x, samp1.y))
   user  system elapsed 
 12.266   0.187  12.465 
> 
> # AUCs
> res1
  modnames dsids curvetypes      aucs
1       m1     1        ROC 0.5001143
2       m1     1        PRC 0.5001206
> res2
[1] 0.5001143
```

**Comment by mfrasco** [comment]
Thanks for responding. I think that using the C++ version of rank in precrec is a good idea. You can quickly test an implementation of the U function with a fast version of the rank function by using `data.table::frank`. This is the function that I used when I cited my benchmarking results.

Here is the code:
```
# Test code
library(precrec)
library(data.table)

# A sample of 10,000,000
samp1 <- create_sim_samples(1, 5000000, 5000000)
scores1 <- samp1$scores[[1]][[1]]
samp1.x <- scores1[1:5000000]
samp1.y <- scores1[5000001:10000000]

# Precrec
func_precrec <- function(samp) {
    curves <- evalmod(scores = samp$scores, labels = samp$labels)
    aucs <- auc(curves)
}

# U statistic
func_u <- function(x, y) {
    n.x <- as.numeric(length(x))
    n.y <- as.numeric(length(y))
    r <- data.table::frank(c(x, y))
    U <- sum(r[seq_along(x)]) - n.x * (n.x + 1) / 2
    uauc <- U / (n.x * n.y)
}
```

And here are the results. I am using OS X - i7, 2.9 Ghz, 8 GB
```
> system.time(res1 <- func_precrec(samp1))
   user  system elapsed 
  6.674   0.639   7.403 
> system.time(res2 <- func_u(samp1.x, samp1.y))
   user  system elapsed 
  0.921   0.062   0.988 
> res1
  modnames dsids curvetypes      aucs
1       m1     1        ROC 0.5000407
2       m1     1        PRC 0.4999557
> res2
[1] 0.5000407
```

And for more benchmarking results:
```
library(microbenchmark)

results <- microbenchmark(precrec = func_precrec(samp1)
                          , U = func_u(samp1.x, samp1.y)
                          , times = 10)
> results
Unit: milliseconds
    expr       min        lq     mean   median       uq      max neval
 precrec 7103.8628 7142.4878 7331.533 7316.634 7525.992 7619.682    10
       U  929.4241  995.1991 1151.190 1232.116 1276.487 1288.051    10
> 
```

Of course, precrec providing much more than just the area under the ROC curve. Your package is amazingly fast. Thank you for making it.

**Comment by mfrasco** [comment]
For some context
```
results <- microbenchmark(fast = data.table::frank(scores1)
                          , slow = rank(scores1)
                          , times = 10)
> results
Unit: milliseconds
 expr        min         lq       mean     median         uq       max neval
 fast   846.4778   867.6792   915.3753   903.9915   950.9837  1033.376    10
 slow 10637.9257 10893.4193 11599.9706 11323.6267 12039.8657 13325.779    10
```

You will be able to speed up `precrec::evalmod` by taking advantage of this algorithm. However, since `precrec:evalmod` also calculates the entire ROC and PR curves, it will never be as fast as `func_u`. Would you be interested in adding a new function to the package that only calculates the area under the ROC curve using this fast algorithm?

**Comment by takayasaito** [comment]
Thanks for your quick reply. It is quite fast with `data.table::frank`, isn't it?

The `evalmod` function currently accepts two different modes, and I'm planning to add a new one for the AUC calculation with the U statistic.
- `rocprc` (default): ROC and precision-recall curves
- `basic`: basic performance metrics
- `aucroc` (new): AUCs (ROC) without curves

**Comment by mfrasco** [comment]
That makes perfect sense. I like the idea to add a new mode to `evalmod`.

**Comment by takayasaito** [comment]
I've added the new `aucroc` mode to the `evalmod` function. It is around 2-3 times faster than the original versoin with the curve calculations. I'll include this enhancement in the next release.

```R
library(precrec)
library(data.table)

# A sample of 10,000,000
samp1 <- create_sim_samples(1, 5000000, 5000000)

# mode = "rocprc"
func_evalmod_rocprc <- function(samp) {
   curves <- evalmod(scores = samp$scores, labels = samp$labels)
   aucs <- auc(curves)
}

# mode = "aucroc"
func_evalmod_aucroc <- function(samp) {
   uaucs <- evalmod(scores = samp$scores, labels = samp$labels, mode="aucroc")
   as.data.frame(uaucs)
}
```

Linux - i7, 3.4GHz, 16 GB
```R
> # Process time
> system.time(res1 <- func_evalmod_rocprc(samp1))
   user  system elapsed 
  3.857   0.388   4.248 
> system.time(res2 <- func_evalmod_aucroc(samp1))
   user  system elapsed 
  1.552   0.062   1.613 
> 
> # AUCs
> res1
  modnames dsids curvetypes      aucs
1       m1     1        ROC 0.5000810
2       m1     1        PRC 0.4999456
> res2
  modnames dsids     aucs       ustats
1       m1     1 0.500081 1.250202e+13
```

I tried two diffrent approches to implemnt the U statitic calcuation.
1. Use `data.table::frank`
2. Sort positives and negatives separately by `std::sort` and merge them

Precrec uses `data.table::frank` by default and `std::sort` when the `data.table` package is not available.
```R
# data.table::fank
func_u_rank <- function(samp) {
   scores <- samp$scores[[1]][[1]]
   labels <- samp$labels
   res <- calc_auc_with_u(scores = scores, labels = labels)
   res$auc
}

# C++ std::sort
func_u_sort <- function(samp) {
   scores <- samp$scores[[1]][[1]]
   labels <- samp$labels
   res <- calc_auc_with_u(scores = scores, labels = labels, ustat_method = "sort")
   res$auc
}
```

Linux - i7, 3.4GHz, 16 GB
```R
> # Process time
> system.time(res3 <- func_u_rank(samp1))
   user  system elapsed 
  1.324   0.048   1.371 
> system.time(res4 <- func_u_sort(samp1))
   user  system elapsed 
  1.391   0.036   1.426 
> 
> # AUCs
> res3
[1] 0.500081
> res4
[1] 0.500081
```
